cp bo_f_2d.txt bo_fSS_2d.txt
cp bo_pa_f_2d.txt bo_pa_fSS_2d.txt
cp bnh4_f_2d.txt bnh4_fSS_2d.txt
cp bno2_f_2d.txt bno2_fSS_2d.txt
cp bdno3_f_2d.txt bdno3_fSS_2d.txt
cp bdno2_f_2d.txt bdno2_fSS_2d.txt
cp bdn2o_f_2d.txt bdn2o_fSS_2d.txt
cp bana_f_2d.txt bana_fSS_2d.txt
cp d_f_2d.txt d_fSS_2d.txt
cp dom_f_2d.txt dom_fSS_2d.txt
cp nh4_f_2d.txt nh4_fSS_2d.txt
cp no2_f_2d.txt no2_fSS_2d.txt
cp no3_f_2d.txt no3_fSS_2d.txt
cp n2o_f_2d.txt n2o_fSS_2d.txt
cp o_f_2d.txt o_fSS_2d.txt
cp zoo_f_2d.txt zoo_fSS_2d.txt
cp zoo2_f_2d.txt zoo2_fSS_2d.txt
cp zoo3_f_2d.txt zoo3_fSS_2d.txt
cp p1_f_2d.txt p1_fSS_2d.txt
cp p2_f_2d.txt p2_fSS_2d.txt
cp p3_f_2d.txt p3_fSS_2d.txt
cp sumall_f_2d.txt sumall_fSS_2d.txt
cp time_f_2d.txt time_fSS_2d.txt
cp y_f_2d.txt y_fSS_2d.txt
cp z_f_2d.txt z_fSS_2d.txt
